--База данных сконфигурирована на стороннем хостинге,
--поэтому её создание не отображено в коде.

--Создание структуры базы данных было проведено с
--использованием СУБД PostgreSQL и соответствующей
--версии языка SQL.

--Создание сущности "Пользователь"
CREATE TABLE t_user(id int generated by default as identity primary key,
username varchar(10) not null unique,
passHash varchar(128) not null,
userRole int not null);

--Создание сущности "Группа"
CREATE TABLE t_group(id int generated by default as identity primary key,
groupName varchar(8));

--Создание сущности "Расписание на неделю"
CREATE TABLE t_weekshedule(id int generated by default as identity primary key,
groupId int references t_group(id) on delete cascade,
down bool default false);

--Создание сущности "График"
CREATE TABLE t_timeshedule(id int generated by default as identity primary key,
firstPair varchar(11) not null, secondPair varchar(11) not null,
thirdPair varchar(11) not null, fourthPair varchar(11) not null,
fifthPair varchar(11) not null, sixthPair varchar(11) not null);

--Создание сущности "Расписание на день"
CREATE TABLE t_dayshedule(id int generated by default as identity primary key,
dayNum int CHECK (dayNum > 0 AND dayNum < 32), monthNum int CHECK (monthNum > 0 AND monthNum < 13),
weekShedule int references t_weekshedule(id) on delete cascade,
weekday int CHECK (weekday > 0 AND weekday < 7));

--Создание сущности "Кабинет"
CREATE TABLE t_room(id varchar primary key);

--Создание сущности "Дисциплина"
CREATE TABLE t_subject(id int generated by default as identity primary key,
name varchar(100) not null);

--Создание сущности "Преподаватель"
CREATE TABLE t_teacher(id int generated by default as identity primary key,
name varchar(100) not null);

--Создание сущности "Занятие"
CREATE TABLE t_pair(id int generated by default as identity primary key,
dayshedule int not null references t_dayshedule(id) on delete cascade,
queue int not null, --1-6
subject int references t_subject(id) on delete set null,
teacher int references t_teacher(id) on delete set null,
room varchar references t_room(id) on delete set null);

create table t_replacement(id int primary key,
dt date not null,
groupid int not null references t_group on delete cascade);

create table t_replacementPair(id int primary key,
replacement int references t_replacement on delete cascade,
queue int check (queue > 0 and queue < 7) not null,
subject text,
teacher text,
room text);

create table t_message(
  id int primary key generated always as identity,
  receiver text not null,
  title text not null,
  body text not null);